<?php

/**
 * @file
 * Helfi_hakuvahti.
 *
 *  Helfi_hakuvahti.module.
 */

declare(strict_types=1);

/**
 * Implements hook_theme().
 */
function helfi_hakuvahti_theme(): array {
  return [
    'hakuvahti_form' => [
      'variables' => [
        'title' => NULL,
        'message' => NULL,
        'autosubmit' => FALSE,
        'button_text' => NULL,
        'action_url' => NULL,
      ],
    ],
    'hakuvahti_confirmation' => [
      'variables' => [
        'title' => NULL,
        'message' => NULL,
        'link' => NULL,
      ],
    ],
  ];
}
