const IndexFields = {
  LANGUAGE: '_language',
  CONTINUOUS: 'is_continuous',
  COPIED: 'field_copied',
  EMPLOYMENT: 'field_employment',
  EMPLOYMENT_ID: 'employment_id',
  EMPLOYMENT_TYPE: 'field_employment_type',
  EMPLOYMENT_TYPE_ID: 'employment_type_id',
  ENTITY_TYPE: 'entity_type',
  INTERNSHIP: 'is_internship',
  JOB_DURATION: 'field_job_duration',
  NUMBER_OF_JOBS: 'field_jobs',
  ORGANIZATION: 'field_organization',
  ORGANIZATION_NAME: 'field_organization_name',
  POSTAL_AREA: 'field_postal_area',
  PUBLICATION_STARTS: 'field_publication_starts',
  RECRUITMENT_TYPE: 'field_recruitment_type',
  SUMMER_JOB: 'is_summer_job',
  TASK_AREA: 'field_task_area',
  LANGCODE: 'langcode',
  STATUS: 'status',
  TID: 'tid',
  TITLE: 'title',
  YOUTH_SUMMER_JOB: 'is_youth_summer_job',
  UNPUBLISH_ON: 'unpublish_on',
  UUID: 'uuid',
};

export default IndexFields;
