_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
ignored_config_entities:
  - 'eu_cookie_compliance.cookie_category*'
  - hdbt_admin_tools.site_settings
  - 'system.site:page.front'
  - 'helfi_rekry_content.job_listings:search_page'
  - 'helfi_rekry_content.job_listings:redirect_403_page'
