_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
ignored_config_entities:
  - 'eu_cookie_compliance.cookie_category*'
  - hdbt_admin_tools.site_settings
  - 'system.site:page.front'
