_core:
  default_config_hash: Q-rouGjsZPL2nUPOuO0OkaDr7ft6gsrH2UfbJ5w08TE
langcode: en
site_settings:
  default_icon: abstract-2
  theme_color: coat-of-arms
  koro: basic
footer_settings:
  footer_color: dark
path_to_json: /themes/contrib/hdbt/src/icons/editor-selectable-icons.json
