_core:
  default_config_hash: 3ooO-bLkru7Jl91Kb8hO7pD1divveu98PTIZQiCV3pQ
langcode: en
site_settings:
  default_icon: abstract-2
  theme_color: coat-of-arms
  koro: basic
footer_settings:
  footer_color: dark
  footer_top_title: Connect
  footer_top_content:
    value: "<ul class=\"menu\">\r\n\t<li class=\"menu__item menu__item--external\"><a class=\"link\" data-design=\"link\" data-link-text=\"Contact the City of Helsinki\" data-protocol=\"false\" href=\"https://www.hel.fi/en/decision-making/contact-us/helsinki-info\">Contact the City of Helsinki</a></li>\r\n\t<li class=\"menu__item menu__item--external\"><a class=\"link\" data-design=\"link\" data-link-text=\"Helsinki-info advisory service\" data-protocol=\"false\" href=\"https://www.hel.fi/kanslia/neuvonta-en/\">Helsinki-info advisory service</a></li>\r\n\t<li class=\"menu__item menu__item--external\"><a class=\"link\" data-design=\"link\" data-link-text=\"Contact information search\" data-protocol=\"false\" href=\"https://digituki.hel.fi/en\">Digital support</a></li>\r\n\t<li class=\"menu__item menu__item--external\"><a class=\"link\" data-design=\"link\" data-link-text=\"Give feedback\" data-protocol=\"false\" href=\"https://www.hel.fi/feedback/\">Give feedback</a></li>\r\n</ul>\r\n"
    format: full_html
