_core:
  default_config_hash: wsVBmS2iVB6unElbxVQ5TNIUtuMFOAVd6KZqzHGhuqc
entity_type_groups:
  node:
    landing_page:
      basic: basic
      open_graph: open_graph
      twitter_cards: twitter_cards
    page:
      basic: basic
      open_graph: open_graph
      twitter_cards: twitter_cards
