display:
  default:
    display_options:
      filters:
        provided_languages_value:
          group_info:
            group_items:
              1:
                title: 'Näytä vain toimipisteet, joista saa palvelua ruotsiksi.'
